name: 🐞 Bug melden
description: Melde einen Fehler, damit wir ihn beheben können
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du dir die Zeit nimmst, einen Bug zu melden 🙌  
        Bitte fülle die folgenden Felder so genau wie möglich aus.

  - type: input
    id: version
    attributes:
      label: Betroffene Version
      description: Welche Version der Software ist betroffen?
      placeholder: z.B. v1.2.3

  - type: textarea
    id: description
    attributes:
      label: Fehlerbeschreibung
      description: Beschreibe klar und verständlich, was nicht funktioniert.
      placeholder: |
        Was ist passiert?
        Was hast du erwartet?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Schritte zum Reproduzieren
      description: Wie kann man den Fehler reproduzieren?
      placeholder: |
        1. Gehe zu '...'
        2. Klicke auf '...'
        3. Siehe Fehler
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Was sollte stattdessen passieren?

  - type: textarea
    id: logs
    attributes:
      label: Logs / Fehlermeldungen
      description: Falls vorhanden, füge relevante Logs oder Fehlermeldungen ein.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Betriebssystem
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Sonstiges

  - type: input
    id: environment
    attributes:
      label: Umgebung
      description: Browser, Node-Version, Python-Version o. Ä.
      placeholder: z.B. Chrome 120, Node.js 20

  - type: checkboxes
    id: confirmation
    attributes:
      label: Bestätigung
      options:
        - label: Ich habe geprüft, dass dieser Bug noch nicht gemeldet wurde.
          required: true
